source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'webpacker', git: 'https://github.com/rails/webpacker.git'
gem 'devise'
gem 'jquery-rails'
gem 'sqlite3'
gem 'heartlike', path: '../..'
gem 'pry'
gem 'faker'